/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/activity/create-with-image': RouteRecordInfo<'/activity/create-with-image', '/activity/create-with-image', Record<never, never>, Record<never, never>>,
    '/activity/custom-create': RouteRecordInfo<'/activity/custom-create', '/activity/custom-create', Record<never, never>, Record<never, never>>,
    '/activity/view': RouteRecordInfo<'/activity/view', '/activity/view', Record<never, never>, Record<never, never>>,
  }
}
